"""API collection generators: OpenAPI 3.0 and Postman Collection v2.1.

Both formats are derived deterministically from the blueprint's ``api``
section, so they always stay synchronized with the latest blueprint.
"""

from __future__ import annotations

import json
from typing import Any

COLLECTION_FORMATS = ("openapi", "postman")


def _endpoints(blueprint: dict[str, Any]) -> list[dict[str, Any]]:
    return blueprint.get("api", {}).get("endpoints", [])


def _is_auth(endpoint: dict[str, Any]) -> bool:
    auth = str(endpoint.get("authentication") or "").strip().lower()
    return bool(auth) and "none" not in auth


def _operation_id(method: str, path: str) -> str:
    segment = path.strip("/").replace("/", "_").replace("-", "_").replace(".", "_") or "root"
    return f"{method.lower()}_{segment}"


def _tag(path: str) -> str:
    parts = [p for p in path.strip("/").split("/") if p]
    return parts[0] if parts else "default"


def _body_properties(body: dict[str, Any]) -> dict[str, Any]:
    properties: dict[str, Any] = {}
    for key, hint in body.items():
        if key == "...":
            continue
        hint_text = str(hint)
        lowered = hint_text.lower()
        if "array" in lowered or hint_text.startswith("["):
            ptype = "array"
            item_type = "object" if "{" in hint_text else "string"
        elif "number" in lowered or "int" in lowered:
            ptype = "number"
        elif "bool" in lowered:
            ptype = "boolean"
        else:
            ptype = "string"
        prop: dict[str, Any] = {"type": ptype}
        if hint_text and hint_text != ptype and "..." not in hint_text:
            prop["description"] = hint_text
        if ptype == "array":
            prop["items"] = {"type": item_type}
        properties[str(key)] = prop
    return properties


def _responses(endpoint: dict[str, Any]) -> dict[str, Any]:
    responses: dict[str, Any] = {}
    for sc in endpoint.get("status_codes") or []:
        if not isinstance(sc, dict):
            continue
        code = str(sc.get("code") or "").strip()
        if code:
            responses[code] = {"description": sc.get("meaning") or ""}
    if not responses:
        responses["200"] = {"description": "Successful response"}
    if _is_auth(endpoint):
        responses.setdefault("401", {"description": "Unauthorized"})
    return responses


def build_openapi(blueprint: dict[str, Any]) -> dict[str, Any]:
    """Build an OpenAPI 3.0 document from the blueprint's API section."""
    api = blueprint.get("api", {})
    project = blueprint.get("project", {})
    paths: dict[str, Any] = {}

    for ep in _endpoints(blueprint):
        method = str(ep.get("method") or "GET").lower()
        path = str(ep.get("path") or "/")
        if not path.startswith("/"):
            path = f"/{path}"

        operation: dict[str, Any] = {
            "operationId": _operation_id(method, path),
            "summary": ep.get("description") or path,
            "description": ep.get("description") or "",
            "tags": [_tag(path)],
            "responses": _responses(ep),
        }
        if _is_auth(ep):
            operation["security"] = [{"bearerAuth": []}]

        request = ep.get("request") or {}
        query = request.get("query") or {}
        parameters = []
        for name, hint in query.items() if isinstance(query, dict) else []:
            parameter: dict[str, Any] = {"name": str(name), "in": "query", "schema": {"type": "string"}}
            if hint:
                parameter["description"] = str(hint)
            parameters.append(parameter)
        if parameters:
            operation["parameters"] = parameters

        body = request.get("body")
        if isinstance(body, dict) and body:
            schema: dict[str, Any] = {"type": "object", "properties": _body_properties(body)}
            operation["requestBody"] = {
                "required": True,
                "content": {"application/json": {"schema": schema}},
            }

        paths.setdefault(path, {})[method] = operation

    return {
        "openapi": "3.0.3",
        "info": {
            "title": f"{project.get('name', 'Project')} API",
            "version": "1.0.0",
            "description": "API collection generated by the AI Project Builder Agent.",
        },
        "servers": [{"url": api.get("base_url") or "/api/v1"}],
        "security": [{"bearerAuth": []}],
        "components": {
            "securitySchemes": {
                "bearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": api.get("auth", {}).get("method") or "JWT",
                }
            }
        },
        "paths": paths,
    }


def build_postman(blueprint: dict[str, Any]) -> dict[str, Any]:
    """Build a Postman Collection v2.1 document from the blueprint's API section."""
    api = blueprint.get("api", {})
    project = blueprint.get("project", {})
    base_url = api.get("base_url") or "/api/v1"

    items = []
    for ep in _endpoints(blueprint):
        method = str(ep.get("method") or "GET").upper()
        path = str(ep.get("path") or "/")
        if not path.startswith("/"):
            path = f"/{path}"

        headers = [{"key": "Content-Type", "value": "application/json"}]
        if _is_auth(ep):
            headers.append({"key": "Authorization", "value": "Bearer {{token}}"})

        url: dict[str, Any] = {
            "raw": f"{{{{baseUrl}}}}{path}",
            "host": ["{{baseUrl}}"],
        }
        segments = [s for s in path.strip("/").split("/") if s]
        url["path"] = segments or []
        query = (ep.get("request") or {}).get("query") or {}
        if isinstance(query, dict) and query:
            url["query"] = [
                {"key": str(key), "value": str(value), "description": str(value)}
                for key, value in query.items()
            ]

        request: dict[str, Any] = {
            "method": method,
            "header": headers,
            "url": url,
            "description": ep.get("description") or "",
        }
        body = (ep.get("request") or {}).get("body")
        if isinstance(body, dict) and body:
            request["body"] = {
                "mode": "raw",
                "raw": json.dumps(body, indent=2, ensure_ascii=False),
                "options": {"raw": {"language": "json"}},
            }
        items.append({"name": f"{method} {path}", "request": request})

    return {
        "info": {
            "name": f"{project.get('name', 'Project')} API",
            "description": "Postman collection generated by the AI Project Builder Agent.",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
        },
        "variable": [
            {"key": "baseUrl", "value": base_url},
            {"key": "token", "value": ""},
        ],
        "item": items,
    }
