"""Single compatibility layer between stored legacy blueprints and the V3 contract.

Legacy blueprints (metadata.version 1.x / 2.x) were generated by an earlier
pipeline and lack sections that current consumers (frontend, exporters, code
generators, diagram and PM services) expect. This module is the ONLY place
that bridges those gaps. It never invents content: sections that simply do not
exist in a legacy blueprint are filled with explicit, honest "not available in
this legacy blueprint" stubs, while every piece of information that IS present
is preserved verbatim (including legacy-only sections such as
``folder_structure`` and ``git_commits``, which are kept as extra keys).

Normalization is applied at the API boundary so stored data is never mutated.
It is idempotent: ``normalize_blueprint(normalize_blueprint(x)) == normalize_blueprint(x)``
and a complete V3 blueprint passes through unchanged.
"""

from __future__ import annotations

import copy
from typing import Any

#: Canonical V3 section keys, in the order the markdown exporter renders them.
CANONICAL_SECTIONS: list[str] = [
    "analysis",
    "domain_understanding",
    "business_processes",
    "technology_selection",
    "technology_evaluation",
    "design_decisions",
    "tradeoffs",
    "architecture",
    "database",
    "api",
    "ui_ux",
    "security",
    "performance",
    "scalability",
    "cost_estimation",
    "business_risks",
    "roadmap",
    "product_evolution",
    "adr",
    "testing",
    "documentation",
    "deployment",
    "validation",
]

#: Sections that only existed in legacy blueprints. Kept for documentation;
#: normalization preserves every non-canonical key verbatim, so no
#: information is ever dropped.
LEGACY_SECTIONS: list[str] = ["folder_structure", "git_commits", "recommendations"]

_CANONICAL_SET = frozenset(CANONICAL_SECTIONS)


class BlueprintIncompatibleError(ValueError):
    """Raised when a stored blueprint cannot be canonicalized to the V3 contract.

    This is an *expected* failure mode (malformed or non-object blueprint data)
    and is mapped to HTTP 400 by the API layer.
    """


def detect_blueprint_version(blueprint: dict[str, Any]) -> str:
    """Return the blueprint version, preferring ``metadata.version``.

    Falls back to a structural heuristic when the metadata is missing or
    malformed: full V3 section set -> "3.0"; domain/technology sections
    present -> "2.0"; otherwise "1.0".
    """
    metadata = blueprint.get("metadata")
    if isinstance(metadata, dict):
        version = str(metadata.get("version") or "").strip()
        if version:
            return version
    keys = set(blueprint.keys())
    if keys >= _CANONICAL_SET:
        return "3.0"
    if "domain_understanding" in keys and "technology_selection" in keys:
        return "2.0"
    return "1.0"


def is_canonical_v3(blueprint: dict[str, Any]) -> bool:
    """True when the blueprint already satisfies the full V3 contract."""
    if not isinstance(blueprint, dict):
        return False
    if not all(section in blueprint for section in CANONICAL_SECTIONS):
        return False
    version = detect_blueprint_version(blueprint)
    return version.split(".")[0] == "3"


def normalize_blueprint(blueprint: dict[str, Any]) -> dict[str, Any]:
    """Return a deep copy of *blueprint* conforming to the V3 contract.

    - Complete V3 blueprints pass through unchanged (idempotent passthrough).
    - Legacy blueprints gain stub sections for every missing canonical key.
    - All present data (including legacy-only sections) is preserved verbatim.
    - ``metadata.legacy_version`` records the source version for pre-V3 input.

    Raises ``BlueprintIncompatibleError`` for non-object blueprint data.
    """
    if not isinstance(blueprint, dict):
        raise BlueprintIncompatibleError(
            "Blueprint is not a structured object and cannot be processed."
        )
    working = copy.deepcopy(blueprint)

    if is_canonical_v3(working):
        return working

    version = detect_blueprint_version(working)
    normalized: dict[str, Any] = {}
    for section in CANONICAL_SECTIONS:
        value = working.get(section)
        normalized[section] = value if isinstance(value, dict) else _legacy_stub(section, version)
    # Every other top-level key (project, metadata, legacy-only sections such
    # as folder_structure/git_commits/recommendations, custom fields) is
    # copied through verbatim so normalization never loses information.
    for key, value in working.items():
        if key not in normalized:
            normalized[key] = value

    _apply_legacy_derivations(normalized, version)

    if version.split(".")[0] != "3":
        metadata = normalized.get("metadata")
        if isinstance(metadata, dict):
            metadata["legacy_version"] = version
        else:
            normalized["metadata"] = {"legacy_version": version}
    return normalized


def _legacy_stub(section: str, version: str) -> dict[str, Any]:
    """Honest placeholder for a section that does not exist in a legacy blueprint."""
    return {
        "summary": (
            f"This section is not present in the legacy blueprint (version {version}). "
            "Regenerate the blueprint to populate it."
        ),
        "available": False,
        "legacy_notice": True,
    }


def _apply_legacy_derivations(blueprint: dict[str, Any], version: str) -> None:
    """Deterministically map legacy data into V3 shapes where it exists.

    Only rearranges information already present in the blueprint; never adds
    new facts. The V1 ``complexity_analysis`` shape is mapped onto the V3
    ``complexity_score`` shape so exports and the frontend render it.
    """
    if version.split(".")[0] == "3":
        return
    analysis = blueprint.get("analysis")
    if not isinstance(analysis, dict):
        return
    if isinstance(analysis.get("complexity_analysis"), dict) and not isinstance(
        analysis.get("complexity_score"), dict
    ):
        complexity = analysis["complexity_analysis"]
        analysis["complexity_score"] = {
            "score": None,
            "level": complexity.get("overall"),
            "reasoning": "; ".join(str(factor) for factor in complexity.get("factors") or []),
            "estimated_time": analysis.get("estimated_development_time"),
            "estimated_team": {
                "roles": [],
                "total": analysis.get("estimated_team_size"),
            },
        }
